modules:
  - name:'application'
paths:
  jquery: 'jq.mobi'
  jqui: 'jq.ui'
  underscore: 'underscore'
  backbone: 'backbone'

shim:
  underscore:
    exports: '_'
  backbone:
    deps: [ 'underscore', 'jquery']
    exports: 'Backbone'
  jquery:
    exports: 'jq'
  jqui: 
    deps: ['jquery']